### ISSUE TITLE
Words for colours support when defining labels

### ISSUE THREAD

**Issue by mariocj89** [Mariocj89/dothub#43]
At the moment writing new labels is not intuitive as it requires to write the colors using their hex code. See:
```
labels:
  bug:
    color: 000000
  enhancement:
    color: ff0000
```

Whilst some gifted minds are able to map those to common word colors normal humans prefer words like "red", "blue", etc.

This issue is to add support so the most common colors can be also specified as words. For ease of implementation, those will be also retrieved as a word at retrieve time. An option to dothub should be added in the future to deactivate this functionality.

The objective is to be able to configure the labels as:

```
labels:
  bug:
    color: black
  enhancement:
    color: red
```
